### ISSUE TITLE
|help command 'undefined'

### ISSUE THREAD

**Issue by old-df38257622** [Grosserly/bipolar#15]
When |help is run, the help is DMed to the user, but there are also some odd 'undefined's laying around:
[image](https://user-images.githubusercontent.com/46039037/72173351-f49bfe00-339c-11ea-9ef0-1bbfea0f8216.png)

**Comment by nate-kean** [comment]
Fixed in commit #158! https://github.com/Grosserly/schism/commit/673b6886edbe160bcd85937ebce8978893c547f7
