### ISSUE TITLE
Bug: Quickstart command is returning attribute error

### ISSUE THREAD

**Issue by majso** [Grosserly/bipolar#60]
Hey,

When running command quickstart I am getting following error:

Command raised an exception: AttributeError: 'coroutine' object has no attribute 'history'

**Comment by old-df38257622** [comment]
Can confirm:
![image](https://github.com/garlic-os/parrot/assets/46039037/981e2d96-17e9-4d01-8ec9-7064c8959a8e)

**Comment by nate-kean** [comment]
Fixed in #62. Sorry for taking so long on this
